esphome:
  name: esp32_2432s028

esp32:
  board: esp32dev

wifi:
  ssid: "YOUR_SSID"
  password: "YOUR_PASSWORD"
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Fallback AP"

logger:

# API (default settings)
api:

# OTA: specify platform for newer ESPHome versions
ota:
  platform: esphome
# Simple status LED example (adjust pin as needed)
status_led:
  pin:
    number: GPIO2
    inverted: false
